export const state = {
  board: null,
  currentTurn: "white",
  selectedSquare: null,
  legalMovesForSelected: [],
  capturedPieces: { white: [], black: [] },
  lastMove: null,
  enPassantTarget: null,
  moveHistory: [],
  positionHistory: [],
  reviewIndex: null,
  statusMessage: "",
  gameOver: false,
  winner: null,
  gameMode: "human",
  botDifficulty: "hard",
  playerColorChoice: "white",
  playerColor: "white",
  botThinking: false,
  botJobId: 0,
  overlayVisible: true,
  gameStarted: false,
  animateMove: false,
};
